/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rsi;

import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class LoginUI extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    public LoginUI() {
    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        simpanButton = new javax.swing.JButton();
        daftarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Famify");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(1440, 900));
        setMinimumSize(new java.awt.Dimension(1440, 900));
        setPreferredSize(new java.awt.Dimension(1440, 900));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Property 1=Default.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 186, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel3.setText("EMAIL");
        jLabel3.setPreferredSize(new java.awt.Dimension(655, 21));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel4.setText("Kata Sandi");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setPreferredSize(new java.awt.Dimension(658, 21));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 406, -1, -1));

        emailTextField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        emailTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        emailTextField.setText("Ketik email...");
        emailTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        emailTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        emailTextField.setPreferredSize(new java.awt.Dimension(658, 61));
        emailTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        emailTextField.setSelectionColor(new java.awt.Color(255, 255, 255));
        emailTextField.setVerifyInputWhenFocusTarget(false);
        emailTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailTextFieldMouseClicked(evt);
            }
        });
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 309, -1, -1));
        emailTextField.getAccessibleContext().setAccessibleName("emailTxtField");

        passwordField.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        passwordField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        passwordField.setText("Ketik kata sandi..");
        passwordField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        passwordField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        passwordField.setOpaque(true);
        passwordField.setPreferredSize(new java.awt.Dimension(658, 61));
        passwordField.setSelectionColor(new java.awt.Color(255, 255, 255));
        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldMouseClicked(evt);
            }
        });
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 435, -1, -1));
        passwordField.getAccessibleContext().setAccessibleName("PassPsField");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/girl-with-red-hat-f4_Obgjio9Y-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, -1, -1));

        simpanButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button.png"))); // NOI18N
        simpanButton.setBorderPainted(false);
        simpanButton.setContentAreaFilled(false);
        simpanButton.setPreferredSize(new java.awt.Dimension(135, 55));
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });
        getContentPane().add(simpanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 532, -1, -1));
        simpanButton.getAccessibleContext().setAccessibleName("LoginButton");

        daftarButton.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        daftarButton.setForeground(new java.awt.Color(11, 177, 203));
        daftarButton.setText("Daftar");
        daftarButton.setBorderPainted(false);
        daftarButton.setContentAreaFilled(false);
        daftarButton.setFocusPainted(false);
        daftarButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        daftarButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        daftarButton.setPreferredSize(new java.awt.Dimension(655, 21));
        daftarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(daftarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 623, 80, -1));
        daftarButton.getAccessibleContext().setAccessibleName("RegisterButton");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Belum punya akun?       \n");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel2.setPreferredSize(new java.awt.Dimension(658, 21));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 623, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        if((emailTextField.getText().equals("Ketik email...") || emailTextField.getText().isBlank()) &&
           (passwordField.getText().equals("Ketik kata sandi..") || passwordField.getText().isBlank())){               
            Aplikasi.controllerLogin.showMessage("Lengkapi Email dan Password Anda");
            emailTextField.setText("Ketik email...");
            passwordField.setText("Ketik kata sandi..");
        }else if (emailTextField.getText().equals("Ketik email...") || emailTextField.getText().isBlank()){
            Aplikasi.controllerLogin.showMessage("Lengkapi Email Anda");
            emailTextField.setText("Ketik email...");
            passwordField.setText("Ketik kata sandi..");
        }else if(passwordField.getText().equals("Ketik kata sandi..") || passwordField.getText().isBlank()){
             Aplikasi.controllerLogin.showMessage("Lengkapi Password Anda");
             emailTextField.setText("Ketik email...");
            passwordField.setText("Ketik kata sandi..");
        }else{        
            Aplikasi.controllerLogin.validateUser(emailTextField.getText(), passwordField.getText());
        }
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void daftarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarButtonActionPerformed
        Aplikasi.dialogUI.showMessage("Fitur ini tidak dikembangkan");// TODO add your handling code here:
    }//GEN-LAST:event_daftarButtonActionPerformed

    private void emailTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTextFieldMouseClicked
        emailTextField.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldMouseClicked

    private void passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseClicked
        passwordField.setText("");    // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldMouseClicked

    public JPasswordField getPasswordField() {
        return passwordField;
    }

    public JTextField getEmailTextField() {
        return emailTextField;
    }
    
    public void tampilkan(){
        this.setVisible(true);
    }
   
         
    /**
     * @param args the command line arguments
     */

     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton daftarButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton simpanButton;
    // End of variables declaration//GEN-END:variables

}