/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rsi;

import java.io.File;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.List;
import java.util.concurrent.TimeUnit;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.SwingWorker;

/**
 *
 * @author ASUS
 */
public class ManajemenKontenUI extends javax.swing.JFrame {
    
    private String currentShowing = "all";
    private int pageArtikel =1;
    private int pageVideo =1;
    private int pageAll =1;

    /**
     * Creates new form ManajemenKontenUI
     */
    public ManajemenKontenUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jButton15 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jButton18 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jButton21 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jButton24 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setDoubleBuffered(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1379, 995));
        jPanel2.setPreferredSize(new java.awt.Dimension(1379, 995));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setDoubleBuffered(false);
        jPanel6.setEnabled(false);
        jPanel6.setFocusable(false);
        jPanel6.setOpaque(false);
        jPanel6.setRequestFocusEnabled(false);
        jPanel6.setVerifyInputWhenFocusTarget(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sampah.png"))); // NOI18N
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setFocusPainted(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, -1, -1));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pencil.png"))); // NOI18N
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setFocusPainted(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        jScrollPane7.setBorder(null);
        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane7.setEnabled(false);
        jScrollPane7.setFocusable(false);
        jScrollPane7.setOpaque(false);
        jScrollPane7.setWheelScrollingEnabled(false);

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 23)); // NOI18N
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(2);
        jTextArea5.setText("Membangun Kesehatan Mental Bayi");
        jTextArea5.setAutoscrolls(false);
        jTextArea5.setBorder(null);
        jTextArea5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea5.setFocusable(false);
        jScrollPane7.setViewportView(jTextArea5);

        jPanel6.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 400, 40));

        jScrollPane8.setBorder(null);
        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane8.setFocusable(false);
        jScrollPane8.setOpaque(false);
        jScrollPane8.setWheelScrollingEnabled(false);

        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea6.setForeground(new java.awt.Color(111, 110, 110));
        jTextArea6.setRows(5);
        jTextArea6.setText("Mengasuh bayi yang baru lahir adalah tugas yang berat dan orang tua akan \nmerasakan berbagai macam emosi. Bahagia bercampur dengan frustrasi, \nkeletihan, dan kecemasan. Emosi yang bercampur-aduk ini sama sekali tak \nperlu ditakuti...");
        jTextArea6.setAutoscrolls(false);
        jTextArea6.setBorder(null);
        jTextArea6.setFocusable(false);
        jScrollPane8.setViewportView(jTextArea6);

        jPanel6.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 670, 100));

        jButton15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jButton15.setForeground(new java.awt.Color(34, 184, 185));
        jButton15.setText("Baca Selengkapnya..");
        jButton15.setActionCommand("");
        jButton15.setBorder(null);
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 130, 220, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 1 (2).png"))); // NOI18N
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 270, 150));

        jLabel3.setText("jLabel3");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/div.u-border-general--bottom.png"))); // NOI18N
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel14.setPreferredSize(new java.awt.Dimension(1319, 197));
        jLabel14.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 107, -1, -1));

        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setDoubleBuffered(false);
        jPanel7.setEnabled(false);
        jPanel7.setFocusable(false);
        jPanel7.setOpaque(false);
        jPanel7.setRequestFocusEnabled(false);
        jPanel7.setVerifyInputWhenFocusTarget(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sampah.png"))); // NOI18N
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.setFocusPainted(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, -1, -1));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pencil.png"))); // NOI18N
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.setFocusPainted(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        jScrollPane9.setBorder(null);
        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane9.setEnabled(false);
        jScrollPane9.setFocusable(false);
        jScrollPane9.setOpaque(false);
        jScrollPane9.setWheelScrollingEnabled(false);

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 23)); // NOI18N
        jTextArea7.setRows(2);
        jTextArea7.setText("Membangun Kesehatan Mental Bayi");
        jTextArea7.setAutoscrolls(false);
        jTextArea7.setBorder(null);
        jTextArea7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea7.setFocusable(false);
        jScrollPane9.setViewportView(jTextArea7);

        jPanel7.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 400, 40));

        jScrollPane10.setBorder(null);
        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane10.setFocusable(false);
        jScrollPane10.setOpaque(false);
        jScrollPane10.setWheelScrollingEnabled(false);

        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea8.setForeground(new java.awt.Color(111, 110, 110));
        jTextArea8.setRows(5);
        jTextArea8.setText("Mengasuh bayi yang baru lahir adalah tugas yang berat dan orang tua akan \nmerasakan berbagai macam emosi. Bahagia bercampur dengan frustrasi, \nkeletihan, dan kecemasan. Emosi yang bercampur-aduk ini sama sekali tak \nperlu ditakuti...");
        jTextArea8.setAutoscrolls(false);
        jTextArea8.setBorder(null);
        jTextArea8.setFocusable(false);
        jScrollPane10.setViewportView(jTextArea8);

        jPanel7.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 670, 100));

        jButton18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jButton18.setForeground(new java.awt.Color(34, 184, 185));
        jButton18.setText("Baca Selengkapnya..");
        jButton18.setActionCommand("");
        jButton18.setBorder(null);
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 130, 220, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 45.png"))); // NOI18N
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 270, 150));

        jLabel4.setText("jLabel4");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/div.u-border-general--bottom.png"))); // NOI18N
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel15.setPreferredSize(new java.awt.Dimension(1319, 197));
        jLabel15.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 307, -1, -1));

        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setDoubleBuffered(false);
        jPanel8.setEnabled(false);
        jPanel8.setFocusable(false);
        jPanel8.setOpaque(false);
        jPanel8.setRequestFocusEnabled(false);
        jPanel8.setVerifyInputWhenFocusTarget(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sampah.png"))); // NOI18N
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.setFocusPainted(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 20, -1, -1));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pencil.png"))); // NOI18N
        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        jButton20.setFocusPainted(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, -1, -1));

        jScrollPane11.setBorder(null);
        jScrollPane11.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane11.setEnabled(false);
        jScrollPane11.setFocusable(false);
        jScrollPane11.setOpaque(false);
        jScrollPane11.setWheelScrollingEnabled(false);

        jTextArea9.setEditable(false);
        jTextArea9.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 23)); // NOI18N
        jTextArea9.setRows(2);
        jTextArea9.setText("Membangun Kesehatan Mental Bayi");
        jTextArea9.setAutoscrolls(false);
        jTextArea9.setBorder(null);
        jTextArea9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea9.setFocusable(false);
        jScrollPane11.setViewportView(jTextArea9);

        jPanel8.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 400, 40));

        jScrollPane12.setBorder(null);
        jScrollPane12.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane12.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane12.setFocusable(false);
        jScrollPane12.setOpaque(false);
        jScrollPane12.setWheelScrollingEnabled(false);

        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea10.setForeground(new java.awt.Color(111, 110, 110));
        jTextArea10.setRows(5);
        jTextArea10.setText("Mengasuh bayi yang baru lahir adalah tugas yang berat dan orang tua akan \nmerasakan berbagai macam emosi. Bahagia bercampur dengan frustrasi, \nkeletihan, dan kecemasan. Emosi yang bercampur-aduk ini sama sekali tak \nperlu ditakuti...");
        jTextArea10.setAutoscrolls(false);
        jTextArea10.setBorder(null);
        jTextArea10.setFocusable(false);
        jScrollPane12.setViewportView(jTextArea10);

        jPanel8.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 670, 100));

        jButton21.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jButton21.setForeground(new java.awt.Color(34, 184, 185));
        jButton21.setText("Baca Selengkapnya..");
        jButton21.setActionCommand("");
        jButton21.setBorder(null);
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        jButton21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 130, 220, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 45.png"))); // NOI18N
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 270, 150));

        jLabel5.setText("jLabel5");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/div.u-border-general--bottom.png"))); // NOI18N
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel16.setPreferredSize(new java.awt.Dimension(1319, 197));
        jLabel16.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 507, -1, -1));

        jPanel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.setDoubleBuffered(false);
        jPanel9.setEnabled(false);
        jPanel9.setFocusable(false);
        jPanel9.setOpaque(false);
        jPanel9.setRequestFocusEnabled(false);
        jPanel9.setVerifyInputWhenFocusTarget(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sampah.png"))); // NOI18N
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.setFocusPainted(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pencil.png"))); // NOI18N
        jButton23.setBorderPainted(false);
        jButton23.setContentAreaFilled(false);
        jButton23.setFocusPainted(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, -1, -1));

        jScrollPane13.setBorder(null);
        jScrollPane13.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane13.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane13.setEnabled(false);
        jScrollPane13.setFocusable(false);
        jScrollPane13.setOpaque(false);
        jScrollPane13.setWheelScrollingEnabled(false);

        jTextArea11.setEditable(false);
        jTextArea11.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea11.setColumns(20);
        jTextArea11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 23)); // NOI18N
        jTextArea11.setRows(2);
        jTextArea11.setText("Membangun Kesehatan Mental Bayi");
        jTextArea11.setAutoscrolls(false);
        jTextArea11.setBorder(null);
        jTextArea11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea11.setFocusable(false);
        jScrollPane13.setViewportView(jTextArea11);

        jPanel9.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 400, 40));

        jScrollPane14.setBorder(null);
        jScrollPane14.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane14.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane14.setFocusable(false);
        jScrollPane14.setOpaque(false);
        jScrollPane14.setWheelScrollingEnabled(false);

        jTextArea12.setColumns(20);
        jTextArea12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea12.setForeground(new java.awt.Color(111, 110, 110));
        jTextArea12.setRows(5);
        jTextArea12.setText("Mengasuh bayi yang baru lahir adalah tugas yang berat dan orang tua akan \nmerasakan berbagai macam emosi. Bahagia bercampur dengan frustrasi, \nkeletihan, dan kecemasan. Emosi yang bercampur-aduk ini sama sekali tak \nperlu ditakuti...");
        jTextArea12.setAutoscrolls(false);
        jTextArea12.setBorder(null);
        jTextArea12.setFocusable(false);
        jScrollPane14.setViewportView(jTextArea12);

        jPanel9.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 670, 100));

        jButton24.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jButton24.setForeground(new java.awt.Color(34, 184, 185));
        jButton24.setText("Baca Selengkapnya..");
        jButton24.setActionCommand("");
        jButton24.setBorder(null);
        jButton24.setBorderPainted(false);
        jButton24.setContentAreaFilled(false);
        jButton24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 130, 220, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 45.png"))); // NOI18N
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 270, 150));

        jLabel6.setText("jLabel6");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, -1));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/div.u-border-general--bottom.png"))); // NOI18N
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel17.setPreferredSize(new java.awt.Dimension(1319, 197));
        jLabel17.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 707, -1, -1));

        jButton7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jButton7.setForeground(new java.awt.Color(34, 184, 185));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 209 (1).png"))); // NOI18N
        jButton7.setText("Semua");
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setRequestFocusEnabled(false);
        jButton7.setRolloverEnabled(false);
        jButton7.setVerifyInputWhenFocusTarget(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 180, -1));

        jButton8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jButton8.setForeground(new java.awt.Color(120, 120, 135));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); // NOI18N
        jButton8.setText("Artikel");
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setFocusPainted(false);
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 40, 174, -1));

        jButton9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jButton9.setForeground(new java.awt.Color(120, 120, 135));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); // NOI18N
        jButton9.setText("Video");
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setFocusPainted(false);
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 40, 178, -1));

        jButton10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jButton10.setForeground(new java.awt.Color(34, 184, 185));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 212 (1).png"))); // NOI18N
        jButton10.setText("    Unggah");
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 40, 176, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn-prev.png"))); // NOI18N
        jButton2.setToolTipText("");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 912, -1, -1));

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn-next.png"))); // NOI18N
        jButton28.setToolTipText("");
        jButton28.setBorder(null);
        jButton28.setBorderPainted(false);
        jButton28.setContentAreaFilled(false);
        jButton28.setFocusPainted(false);
        jButton28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(882, 912, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("1 / 5");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 920, -1, -1));

        jScrollPane2.setViewportView(jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 94));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ellipse 44.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setPreferredSize(new java.awt.Dimension(70, 70));
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1288, 12, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Property 1=Default.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 22, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(111, 110, 110));
        jButton1.setText("Beranda");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPreferredSize(new java.awt.Dimension(78, 15));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 40, 100, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(111, 110, 110));
        jButton3.setText("Manajemen Jadwal");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setPreferredSize(new java.awt.Dimension(180, 15));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(111, 110, 110));
        jButton4.setText("Sesi Konsultasi");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setPreferredSize(new java.awt.Dimension(143, 15));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        jButton29.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        jButton29.setForeground(new java.awt.Color(111, 110, 110));
        jButton29.setText("Obrolan");
        jButton29.setBorderPainted(false);
        jButton29.setContentAreaFilled(false);
        jButton29.setPreferredSize(new java.awt.Dimension(76, 15));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 40, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        ImageIcon iconButton8 = (ImageIcon) jButton8.getIcon();
        ImageIcon iconReference = new ImageIcon(getClass().getResource("/images/Frame 209 (1).png"));
        ImageIcon iconButton9 = (ImageIcon) jButton9.getIcon();

        if (iconButton8 != null && iconButton8.getDescription().equals(iconReference.getDescription())) {
             Aplikasi.delArtikel.hapusArtikelDariDB(jTextArea5.getText());
             List<Artikel> artikels = Aplikasi.controllerManajemen.loadArticle(pageArtikel);
            Aplikasi.controllerManajemen.showArticle(artikels);             
        } else if (iconButton9 != null && iconButton9.getDescription().equals(iconReference.getDescription())){
            Aplikasi.delVidio.hapusVideoDariDB(jTextArea5.getText());
            List<Video> videos = Aplikasi.controllerManajemen.loadVideo(pageVideo);
            Aplikasi.controllerManajemen.showVideo(videos);            
        } else {
           Aplikasi.dialogUI.showMessage("");
        }
       
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        //ini harusnya cek kondisi dulu jenis kontennya artikel atau video?
        // klu artikel manggil editArtikel, klu video manggil edit video
        //logicnya mungkin mirip sm tombol unggah
        //ini blum ada kelas editVideonya sm editVideoController aja
        Aplikasi.editArtikel.tampilkan(jTextArea5.getText(), jLabel3.getText());
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        Aplikasi.lihatKonten.showArticle(jTextArea5.getText());        
        this.dispose();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        ImageIcon iconButton8 = (ImageIcon) jButton8.getIcon();
        ImageIcon iconReference = new ImageIcon(getClass().getResource("/images/Frame 209 (1).png"));
        ImageIcon iconButton9 = (ImageIcon) jButton9.getIcon();

        if (iconButton8 != null && iconButton8.getDescription().equals(iconReference.getDescription())) {
             Aplikasi.delArtikel.hapusArtikelDariDB(jTextArea7.getText());
             List<Artikel> artikels = Aplikasi.controllerManajemen.loadArticle(pageArtikel);
            Aplikasi.controllerManajemen.showArticle(artikels);             
        } else if (iconButton9 != null && iconButton9.getDescription().equals(iconReference.getDescription())){
            Aplikasi.delVidio.hapusVideoDariDB(jTextArea7.getText());
            List<Video> videos = Aplikasi.controllerManajemen.loadVideo(pageVideo);
            Aplikasi.controllerManajemen.showVideo(videos);            
        } else {
           Aplikasi.dialogUI.showMessage("");
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       //ini harusnya cek kondisi dulu jenis kontennya artikel atau video?
        // klu artikel manggil editArtikel, klu video manggil edit video
        //logicnya mungkin mirip sm tombol unggah
        //ini blum ada kelas editVideonya sm editVideoController aja
        Aplikasi.editArtikel.tampilkan(jTextArea5.getText(), jLabel3.getText());
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        Aplikasi.lihatKonten.showArticle(jTextArea7.getText());        
        this.dispose();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        ImageIcon iconButton8 = (ImageIcon) jButton8.getIcon();
        ImageIcon iconReference = new ImageIcon(getClass().getResource("/images/Frame 209 (1).png"));
        ImageIcon iconButton9 = (ImageIcon) jButton9.getIcon();

        if (iconButton8 != null && iconButton8.getDescription().equals(iconReference.getDescription())) {
             Aplikasi.delArtikel.hapusArtikelDariDB(jTextArea9.getText());
             List<Artikel> artikels = Aplikasi.controllerManajemen.loadArticle(pageArtikel);
            Aplikasi.controllerManajemen.showArticle(artikels);             
        } else if (iconButton9 != null && iconButton9.getDescription().equals(iconReference.getDescription())){
            Aplikasi.delVidio.hapusVideoDariDB(jTextArea9.getText());
            List<Video> videos = Aplikasi.controllerManajemen.loadVideo(pageVideo);
            Aplikasi.controllerManajemen.showVideo(videos);            
        } else {
           Aplikasi.dialogUI.showMessage("");
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        //ini harusnya cek kondisi dulu jenis kontennya artikel atau video?
        // klu artikel manggil editArtikel, klu video manggil edit video
        //logicnya mungkin mirip sm tombol unggah
        //ini blum ada kelas editVideonya sm editVideoController aja
        Aplikasi.editArtikel.tampilkan(jTextArea5.getText(), jLabel3.getText());
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        Aplikasi.lihatKonten.showArticle(jTextArea9.getText());        
        this.dispose();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        ImageIcon iconButton8 = (ImageIcon) jButton8.getIcon();
        ImageIcon iconReference = new ImageIcon(getClass().getResource("/images/Frame 209 (1).png"));
        ImageIcon iconButton9 = (ImageIcon) jButton9.getIcon();

        if (iconButton8 != null && iconButton8.getDescription().equals(iconReference.getDescription())) {
             Aplikasi.delArtikel.hapusArtikelDariDB(jTextArea11.getText());
             List<Artikel> artikels = Aplikasi.controllerManajemen.loadArticle(pageArtikel);
            Aplikasi.controllerManajemen.showArticle(artikels);             
        } else if (iconButton9 != null && iconButton9.getDescription().equals(iconReference.getDescription())){
            Aplikasi.delVidio.hapusVideoDariDB(jTextArea11.getText());
            List<Video> videos = Aplikasi.controllerManajemen.loadVideo(pageVideo);
            Aplikasi.controllerManajemen.showVideo(videos);            
        } else {
           Aplikasi.dialogUI.showMessage("");
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        //ini harusnya cek kondisi dulu jenis kontennya artikel atau video?
        // klu artikel manggil editArtikel, klu video manggil edit video
        //logicnya mungkin mirip sm tombol unggah
        //ini blum ada kelas editVideonya sm editVideoController aja
        Aplikasi.editArtikel.tampilkan(jTextArea5.getText(), jLabel3.getText());
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        Aplikasi.lihatKonten.showArticle(jTextArea11.getText());        
        this.dispose();
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        currentShowing = "all";        
        int totalPagesAll = (int) Math.ceil((Aplikasi.article.totalArticle() + Aplikasi.video.totalVideos()) / 4.0);
        if(totalPagesAll==0){
            jLabel1.setText("1/1");
        }else{
            jLabel1.setText("1/"+totalPagesAll);
        }
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 209 (1).png")));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        jButton8.setForeground(new java.awt.Color(120, 120, 135));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        jButton9.setForeground(new java.awt.Color(120, 120, 135));
        jButton7.setForeground(new java.awt.Color(34, 184, 185));
               
        //menampilkan semua
        jButton10.setVisible(false);
        jButton14.setVisible(false);
        jButton17.setVisible(false);
        jButton20.setVisible(false);
        jButton23.setVisible(false);
        Aplikasi.controllerManajemen.showAll(1);        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        currentShowing = "artikel";
        if(Aplikasi.article.getTotalPages()==0){
            jLabel1.setText("1/1");
        }else{
            jLabel1.setText("1/"+Aplikasi.article.getTotalPages());
        }
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 209 (1).png"))); 
        jButton8.setForeground(new java.awt.Color(34, 184, 185));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        jButton7.setForeground(new java.awt.Color(120, 120, 135));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        jButton9.setForeground(new java.awt.Color(120, 120, 135));
      
        //memanggil tampilkanHanya artikel
        if(Aplikasi.akun.getPerson().equals("administrator")){
            jButton10.setVisible(true);
            jButton14.setVisible(true);
            jButton17.setVisible(true);
            jButton20.setVisible(true);
            jButton23.setVisible(true);
            jButton13.setVisible(true);
            jButton16.setVisible(true);
            jButton19.setVisible(true);
            jButton22.setVisible(true);
        }else{
            jButton10.setVisible(false);
        }
        List<Artikel> artikels = Aplikasi.controllerManajemen.loadArticle(1);
        Aplikasi.controllerManajemen.showArticle(artikels);
        //this.dispose();
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        currentShowing ="video";
        if(Aplikasi.video.getTotalPages()==0){
            jLabel1.setText("1/1");
        }else{
            jLabel1.setText("1/"+Aplikasi.video.getTotalPages());
        }
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 209 (1).png"))); 
        jButton9.setForeground(new java.awt.Color(34, 184, 185));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        jButton8.setForeground(new java.awt.Color(120, 120, 135));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        jButton7.setForeground(new java.awt.Color(120, 120, 135));
        
        //memanggil tampilkan hanyaa video
        if(Aplikasi.akun.getPerson().equals("administrator")){
            jButton10.setVisible(true);
            jButton14.setVisible(true);
            jButton17.setVisible(true);
            jButton20.setVisible(true);
            jButton23.setVisible(true);
            jButton13.setVisible(true);
            jButton16.setVisible(true);
            jButton19.setVisible(true);
            jButton22.setVisible(true);
        }else{
            jButton10.setVisible(false);
        }
        List<Video> videos = Aplikasi.controllerManajemen.loadVideo(1);
        Aplikasi.controllerManajemen.showVideo(videos);
        //this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
        JButton temp = new javax.swing.JButton();
        temp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 209 (1).png"))); // NOI18N
        ImageIcon iconButton8 = (ImageIcon) jButton8.getIcon();
        ImageIcon iconReference = new ImageIcon(getClass().getResource("/images/Frame 209 (1).png"));
        ImageIcon iconButton9 = (ImageIcon) jButton9.getIcon();

        if (iconButton8 != null && iconButton8.getDescription().equals(iconReference.getDescription())) {
            Aplikasi.addArticle.showUpArticle();
        } else if (iconButton9 != null && iconButton9.getDescription().equals(iconReference.getDescription())){
            Aplikasi.addVideo.showUpVideo();
        } else {
           Aplikasi.dialogUI.showMessage("");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(currentShowing.equals("all")){
            if(pageAll > 1) {  
                pageAll--;
                int totalPagesAll = (int) Math.ceil((Aplikasi.article.totalArticle() + Aplikasi.video.totalVideos()) / 4.0);
                jLabel1.setText(pageAll + "/" + totalPagesAll );
                Aplikasi.controllerManajemen.showAll(pageAll);
                
            }
        } else if(currentShowing.equals("video")){
            if(pageVideo > 1) {  
                pageVideo--; 
                jLabel1.setText(pageVideo+"/"+Aplikasi.video.getTotalPages());
                List<Video> videos = Aplikasi.controllerManajemen.loadVideo(pageVideo); // Beri parameter pageVideo
                Aplikasi.controllerManajemen.showVideo(videos);
            }
        } else if(currentShowing.equals("artikel")){
            if(pageArtikel > 1) {  
                pageArtikel--;  
                jLabel1.setText(pageArtikel +"/"+Aplikasi.article.getTotalPages());
                List<Artikel> articles = Aplikasi.controllerManajemen.loadArticle(pageArtikel); 
                Aplikasi.controllerManajemen.showArticle(articles);
            }
        }
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        if(currentShowing.equals("all")){           
            int totalPagesAll = (int) Math.ceil((Aplikasi.article.totalArticle() + Aplikasi.video.totalVideos()) / 4.0);
            if (pageAll < totalPagesAll) { 
                pageAll++;
                jLabel1.setText(pageAll + "/" + totalPagesAll );
                Aplikasi.controllerManajemen.showAll(pageAll);
            }
        } else if(currentShowing.equals("video")){
            if(pageVideo+1 <= Aplikasi.video.getTotalPages()){
                pageVideo++;
                jLabel1.setText(pageVideo+"/"+Aplikasi.video.getTotalPages());
                List<Video> videos = Aplikasi.controllerManajemen.loadVideo(pageVideo);
                Aplikasi.controllerManajemen.showVideo(videos);
            }
        }else {
            if(pageArtikel+1 <= Aplikasi.article.getTotalPages()){
                pageArtikel++;
                jLabel1.setText(pageArtikel +"/"+Aplikasi.article.getTotalPages());
                List<Artikel> articles = Aplikasi.controllerManajemen.loadArticle(pageArtikel); 
                Aplikasi.controllerManajemen.showArticle(articles);
            }
        }        
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Aplikasi.beranda.tampilkan();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(Aplikasi.akun.getPerson().contains("k")){
            Aplikasi.dialogUI.showMessage("FITUR INI TIDAK KAMI PROSES");
        }else{
            //manajemen konten
            Aplikasi.controllerManajemen.showAll(pageAll);
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(Aplikasi.akun.getPerson().contains("k")){
            this.dispose();
            Aplikasi.controllerDaftarSesi.load();
        }else{
            Aplikasi.dialogUI.showMessage("FITUR INI TIDAK KAMI PROSES");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        Aplikasi.dialogUI.showMessage("FITUR INI TIDAK KAMI PROSES");
    }//GEN-LAST:event_jButton29ActionPerformed

   
    public void tampilkanArticle(List<Artikel> Articles){        
        int totalPages = Aplikasi.article.getTotalPages();
        List <Artikel> articles = Articles;
                
        
        if(Aplikasi.akun.getPerson().equals("administrator")){
            jButton10.setVisible(true);
        }else{
            jButton10.setVisible(false);
        }
        tampilkan();  
        
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 209 (1).png"))); 
        jButton8.setForeground(new java.awt.Color(34, 184, 185));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        jButton7.setForeground(new java.awt.Color(120, 120, 135));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        jButton9.setForeground(new java.awt.Color(120, 120, 135));
        
        if(articles.size() >=1){
            Artikel artikel = articles.get(0);
            String path = "src/main/resources/images/Thumbnail_db_" + artikel.judul + ".png";
            jLabel28.setIcon(new javax.swing.ImageIcon(path));                     
            jTextArea5.setText(artikel.getJudul());
            jTextArea6.setText(artikel.getIsiArtikel().substring(0,1)+"...");
            jPanel6.setVisible(true);
            jLabel3.setText(artikel.getIdArtikel());
            jLabel3.setVisible(false);
        }
        if(articles.size() >=2){
            Artikel artikel = articles.get(1);
            String path = "src/main/resources/images/Thumbnail_db_" + artikel.judul + ".png";
            jLabel29.setIcon(new javax.swing.ImageIcon(path));         
            jTextArea7.setText(artikel.getJudul());
            jTextArea8.setText(artikel.getIsiArtikel().substring(0,1)+"...");
            jPanel7.setVisible(true);
            jLabel4.setText(artikel.getIdArtikel());
            jLabel4.setVisible(false);
        }
        if(articles.size() >=3){
            Artikel artikel = articles.get(2); 
            String path = "src/main/resources/images/Thumbnail_db_" + artikel.judul + ".png";
            jLabel30.setIcon(new javax.swing.ImageIcon(path));        
            jTextArea9.setText(artikel.getJudul());
            jTextArea10.setText(artikel.getIsiArtikel().substring(0,1)+"...");
            jPanel8.setVisible(true);
            jLabel5.setText(artikel.getIdArtikel());
            jLabel5.setVisible(false);
        }
        if(articles.size() >=4){
            Artikel artikel = articles.get(3);            
            String path = "src/main/resources/images/Thumbnail_db_" + artikel.judul + ".png";
            jLabel31.setIcon(new javax.swing.ImageIcon(path));            
            jTextArea11.setText(artikel.getJudul());
            jTextArea12.setText(artikel.getIsiArtikel().substring(0,1)+"...");
            jPanel9.setVisible(true);
            jLabel6.setText(artikel.getIdArtikel());
            jLabel6.setVisible(false);
        }
        
        this.setVisible(true);
    }
           
    
    public void tampilkanVideo(List<Video> Videos){        
        if(Aplikasi.akun.getPerson().equals("administrator")){
            jButton10.setVisible(true);
        }else{
            jButton10.setVisible(false);
        }
        
        tampilkan(); 
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 209 (1).png"))); 
        jButton9.setForeground(new java.awt.Color(34, 184, 185));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        jButton8.setForeground(new java.awt.Color(120, 120, 135));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        jButton7.setForeground(new java.awt.Color(120, 120, 135));
        
        if(Videos.size()>=1){
            Video video = Videos.get(0);
            String path = "src/main/resources/images/Thumbnail_db_" + video.judul + ".png";
            jLabel28.setIcon(new javax.swing.ImageIcon(path));       
            jTextArea5.setText(video.getJudul());
            String deskripsi = video.getDeskripsi();
            jTextArea6.setText(deskripsi);         
            
            jPanel6.setVisible(true);
        }
        if(Videos.size()>=2){
            Video video = Videos.get(1);
            String path = "src/main/resources/images/Thumbnail_db_" + video.judul + ".png";
            jLabel29.setIcon(new javax.swing.ImageIcon(path));     
            jTextArea7.setText(video.getJudul());
            String deskripsi = video.getDeskripsi();
            jTextArea8.setText(deskripsi);    
            
            jPanel7.setVisible(true);
        }
        if(Videos.size()>=3){
            Video video = Videos.get(2);            
            String path = "src/main/resources/images/Thumbnail_db_" + video.judul + ".png";
            jLabel30.setIcon(new javax.swing.ImageIcon(path));     
            jTextArea9.setText(video.getJudul());
            String deskripsi = video.getDeskripsi();
            jTextArea10.setText(deskripsi);       
            
            jPanel8.setVisible(true);
        }
        if(Videos.size()>=4){
            Video video = Videos.get(3);            
            String path = "src/main/resources/images/Thumbnail_db_" + video.judul + ".png";
            jLabel31.setIcon(new javax.swing.ImageIcon(path));     
            jTextArea11.setText(video.getJudul());
            String deskripsi = video.getDeskripsi();
            jTextArea12.setText(deskripsi);       
            
            jPanel9.setVisible(true);
        }
        
        
        
        this.setVisible(true);
    }
    
    public void tampilkanSemua(List<Content> all){       
        tampilkan();
        int totalPagesAll = (int) Math.ceil((Aplikasi.article.totalArticle() + Aplikasi.video.totalVideos()) / 4.0);
        if(totalPagesAll==0){
            jLabel1.setText("1/1");
        }else{
            jLabel1.setText("1/"+totalPagesAll);
        }
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 209 (1).png"))); 
        jButton7.setForeground(new java.awt.Color(34, 184, 185));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        jButton8.setForeground(new java.awt.Color(120, 120, 135));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        jButton9.setForeground(new java.awt.Color(120, 120, 135));
        
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jButton10.setVisible(false);
        jButton13.setVisible(false);
        jButton14.setVisible(false);
        jButton16.setVisible(false);
        jButton17.setVisible(false);
        jButton19.setVisible(false);
        jButton20.setVisible(false);
        jButton22.setVisible(false);
        jButton23.setVisible(false);
        for (int i = 0; i < Math.min(4, all.size()); i++) {
        Content content = all.get(i);
        String imagePath;
        String description;

        // Tentukan ikon dan teks berdasarkan tipe konten
        if (content instanceof Video video) {
            imagePath = "src/main/resources/images/Thumbnail_db_" + video.getJudul() + ".png";
            description = video.getDeskripsi();
        } else if (content instanceof Artikel artikel) {
            imagePath = "src/main/resources/images/Thumbnail_db_" + artikel.getJudul() + ".png";
            description = artikel.getIsiArtikel().substring(0, Math.min(250, artikel.getIsiArtikel().length())) + "...";
        } else {
            continue; // Jika tipe tidak dikenali, lewati
        }

        // Atur konten ke panel yang sesuai
        switch (i) {
            case 0 -> {
                jLabel28.setIcon(new javax.swing.ImageIcon(imagePath));
                jTextArea5.setText(content.getJudul());
                jTextArea6.setText(description);
                jPanel6.setVisible(true);
            }
            case 1 -> {
                jLabel29.setIcon(new javax.swing.ImageIcon(imagePath));
                jTextArea7.setText(content.getJudul());
                jTextArea8.setText(description);
                jPanel7.setVisible(true);
            }
            case 2 -> {
                jLabel30.setIcon(new javax.swing.ImageIcon(imagePath));
                jTextArea9.setText(content.getJudul());
                jTextArea10.setText(description);
                jPanel8.setVisible(true);
            }
            case 3 -> {
                jLabel31.setIcon(new javax.swing.ImageIcon(imagePath));
                jTextArea11.setText(content.getJudul());
                jTextArea12.setText(description);
                jPanel9.setVisible(true);
            }
        }
    }     
           
        this.setVisible(true);
    }
    
    public void tampilkan(){        
        if(Aplikasi.akun.getPerson().equals("klien")){
            jButton3.setText("Reservasi");
            jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ellipse 44.png")));//mengganti icon
        }else if(Aplikasi.akun.getPerson().equals("administrator")){
            jButton4.setText("Notifikasi");
            jButton29.setVisible(false);
            jButton3.setText("Manajemen Konten");       
            jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ellipse 44.png")));//mengganti profile
        }
        
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        
    }
    
   
    
    
    
    /**
     * @param args the command line arguments
     */

    public JButton getjButton13() {
        return jButton13;
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    // End of variables declaration//GEN-END:variables
}
