/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rsi;

import java.io.File;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.List;
import java.util.concurrent.TimeUnit;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.SwingWorker;

/**
 *
 * @author ASUS
 */
public class ManajemenKontenUI extends javax.swing.JFrame {
    
    private String currentShowing = "all";
    private int pageArtikel =1;
    private int pageVideo =1;
    private int pageAll =1;

    /**
     * Creates new form ManajemenKontenUI
     */
    public ManajemenKontenUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        delete1 = new javax.swing.JButton();
        Edit1 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        judul1 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        desc1 = new javax.swing.JTextArea();
        read1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        delete2 = new javax.swing.JButton();
        edit2 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        judul2 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        desc2 = new javax.swing.JTextArea();
        read2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        delete3 = new javax.swing.JButton();
        edit3 = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        judul3 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        desc3 = new javax.swing.JTextArea();
        read3 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        delete4 = new javax.swing.JButton();
        edit4 = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        judul4 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        desc4 = new javax.swing.JTextArea();
        read4 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        semuaButton = new javax.swing.JButton();
        artikelButton = new javax.swing.JButton();
        videoButton = new javax.swing.JButton();
        unggahButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        berandaButton = new javax.swing.JButton();
        navBarTwo = new javax.swing.JButton();
        navBarThree = new javax.swing.JButton();
        navBarFour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setDoubleBuffered(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1379, 995));
        jPanel2.setPreferredSize(new java.awt.Dimension(1379, 995));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setDoubleBuffered(false);
        jPanel6.setEnabled(false);
        jPanel6.setFocusable(false);
        jPanel6.setOpaque(false);
        jPanel6.setRequestFocusEnabled(false);
        jPanel6.setVerifyInputWhenFocusTarget(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sampah.png"))); // NOI18N
        delete1.setBorderPainted(false);
        delete1.setContentAreaFilled(false);
        delete1.setFocusPainted(false);
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        jPanel6.add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 20, -1));

        Edit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pencil.png"))); // NOI18N
        Edit1.setBorderPainted(false);
        Edit1.setContentAreaFilled(false);
        Edit1.setFocusPainted(false);
        Edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit1ActionPerformed(evt);
            }
        });
        jPanel6.add(Edit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, -1));

        jScrollPane7.setBorder(null);
        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane7.setEnabled(false);
        jScrollPane7.setFocusable(false);
        jScrollPane7.setOpaque(false);
        jScrollPane7.setWheelScrollingEnabled(false);

        judul1.setEditable(false);
        judul1.setBackground(new java.awt.Color(255, 255, 255));
        judul1.setColumns(20);
        judul1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 23)); // NOI18N
        judul1.setLineWrap(true);
        judul1.setRows(2);
        judul1.setText("Membangun Kesehatan Mental Bayi");
        judul1.setAutoscrolls(false);
        judul1.setBorder(null);
        judul1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        judul1.setFocusable(false);
        jScrollPane7.setViewportView(judul1);

        jPanel6.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 400, 40));

        jScrollPane8.setBorder(null);
        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane8.setFocusable(false);
        jScrollPane8.setOpaque(false);
        jScrollPane8.setWheelScrollingEnabled(false);

        desc1.setColumns(20);
        desc1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        desc1.setForeground(new java.awt.Color(111, 110, 110));
        desc1.setLineWrap(true);
        desc1.setRows(5);
        desc1.setText("Mengasuh bayi yang baru lahir adalah tugas yang berat dan orang tua akan \nmerasakan berbagai macam emosi. Bahagia bercampur dengan frustrasi, \nkeletihan, dan kecemasan. Emosi yang bercampur-aduk ini sama sekali tak \nperlu ditakuti...");
        desc1.setAutoscrolls(false);
        desc1.setBorder(null);
        desc1.setFocusable(false);
        jScrollPane8.setViewportView(desc1);

        jPanel6.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 670, 100));

        read1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        read1.setForeground(new java.awt.Color(34, 184, 185));
        read1.setText("Baca Selengkapnya..");
        read1.setActionCommand("");
        read1.setBorder(null);
        read1.setBorderPainted(false);
        read1.setContentAreaFilled(false);
        read1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        read1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read1ActionPerformed(evt);
            }
        });
        jPanel6.add(read1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 130, 220, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 1 (2).png"))); // NOI18N
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 270, 150));

        jLabel3.setText("jLabel3");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/div.u-border-general--bottom.png"))); // NOI18N
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel14.setPreferredSize(new java.awt.Dimension(1319, 197));
        jLabel14.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 107, -1, -1));

        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setDoubleBuffered(false);
        jPanel7.setEnabled(false);
        jPanel7.setFocusable(false);
        jPanel7.setOpaque(false);
        jPanel7.setRequestFocusEnabled(false);
        jPanel7.setVerifyInputWhenFocusTarget(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sampah.png"))); // NOI18N
        delete2.setBorderPainted(false);
        delete2.setContentAreaFilled(false);
        delete2.setFocusPainted(false);
        delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete2ActionPerformed(evt);
            }
        });
        jPanel7.add(delete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, -1, -1));

        edit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pencil.png"))); // NOI18N
        edit2.setBorderPainted(false);
        edit2.setContentAreaFilled(false);
        edit2.setFocusPainted(false);
        edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit2ActionPerformed(evt);
            }
        });
        jPanel7.add(edit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        jScrollPane9.setBorder(null);
        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane9.setEnabled(false);
        jScrollPane9.setFocusable(false);
        jScrollPane9.setOpaque(false);
        jScrollPane9.setWheelScrollingEnabled(false);

        judul2.setEditable(false);
        judul2.setBackground(new java.awt.Color(255, 255, 255));
        judul2.setColumns(20);
        judul2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 23)); // NOI18N
        judul2.setRows(2);
        judul2.setText("Membangun Kesehatan Mental Bayi");
        judul2.setAutoscrolls(false);
        judul2.setBorder(null);
        judul2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        judul2.setFocusable(false);
        jScrollPane9.setViewportView(judul2);

        jPanel7.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 400, 40));

        jScrollPane10.setBorder(null);
        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane10.setFocusable(false);
        jScrollPane10.setOpaque(false);
        jScrollPane10.setWheelScrollingEnabled(false);

        desc2.setColumns(20);
        desc2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        desc2.setForeground(new java.awt.Color(111, 110, 110));
        desc2.setLineWrap(true);
        desc2.setRows(5);
        desc2.setText("Mengasuh bayi yang baru lahir adalah tugas yang berat dan orang tua akan \nmerasakan berbagai macam emosi. Bahagia bercampur dengan frustrasi, \nkeletihan, dan kecemasan. Emosi yang bercampur-aduk ini sama sekali tak \nperlu ditakuti...");
        desc2.setAutoscrolls(false);
        desc2.setBorder(null);
        desc2.setFocusable(false);
        jScrollPane10.setViewportView(desc2);

        jPanel7.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 670, 100));

        read2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        read2.setForeground(new java.awt.Color(34, 184, 185));
        read2.setText("Baca Selengkapnya..");
        read2.setActionCommand("");
        read2.setBorder(null);
        read2.setBorderPainted(false);
        read2.setContentAreaFilled(false);
        read2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        read2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read2ActionPerformed(evt);
            }
        });
        jPanel7.add(read2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 130, 220, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 45.png"))); // NOI18N
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 270, 150));

        jLabel4.setText("jLabel4");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/div.u-border-general--bottom.png"))); // NOI18N
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel15.setPreferredSize(new java.awt.Dimension(1319, 197));
        jLabel15.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 307, -1, -1));

        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setDoubleBuffered(false);
        jPanel8.setEnabled(false);
        jPanel8.setFocusable(false);
        jPanel8.setOpaque(false);
        jPanel8.setRequestFocusEnabled(false);
        jPanel8.setVerifyInputWhenFocusTarget(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sampah.png"))); // NOI18N
        delete3.setBorderPainted(false);
        delete3.setContentAreaFilled(false);
        delete3.setFocusPainted(false);
        delete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete3ActionPerformed(evt);
            }
        });
        jPanel8.add(delete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 20, -1, -1));

        edit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pencil.png"))); // NOI18N
        edit3.setBorderPainted(false);
        edit3.setContentAreaFilled(false);
        edit3.setFocusPainted(false);
        edit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit3ActionPerformed(evt);
            }
        });
        jPanel8.add(edit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, -1, -1));

        jScrollPane11.setBorder(null);
        jScrollPane11.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane11.setEnabled(false);
        jScrollPane11.setFocusable(false);
        jScrollPane11.setOpaque(false);
        jScrollPane11.setWheelScrollingEnabled(false);

        judul3.setEditable(false);
        judul3.setBackground(new java.awt.Color(255, 255, 255));
        judul3.setColumns(20);
        judul3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 23)); // NOI18N
        judul3.setRows(2);
        judul3.setText("Membangun Kesehatan Mental Bayi");
        judul3.setAutoscrolls(false);
        judul3.setBorder(null);
        judul3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        judul3.setFocusable(false);
        jScrollPane11.setViewportView(judul3);

        jPanel8.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 400, 40));

        jScrollPane12.setBorder(null);
        jScrollPane12.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane12.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane12.setFocusable(false);
        jScrollPane12.setOpaque(false);
        jScrollPane12.setWheelScrollingEnabled(false);

        desc3.setColumns(20);
        desc3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        desc3.setForeground(new java.awt.Color(111, 110, 110));
        desc3.setLineWrap(true);
        desc3.setRows(5);
        desc3.setText("Mengasuh bayi yang baru lahir adalah tugas yang berat dan orang tua akan \nmerasakan berbagai macam emosi. Bahagia bercampur dengan frustrasi, \nkeletihan, dan kecemasan. Emosi yang bercampur-aduk ini sama sekali tak \nperlu ditakuti...");
        desc3.setAutoscrolls(false);
        desc3.setBorder(null);
        desc3.setFocusable(false);
        jScrollPane12.setViewportView(desc3);

        jPanel8.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 670, 100));

        read3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        read3.setForeground(new java.awt.Color(34, 184, 185));
        read3.setText("Baca Selengkapnya..");
        read3.setActionCommand("");
        read3.setBorder(null);
        read3.setBorderPainted(false);
        read3.setContentAreaFilled(false);
        read3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        read3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read3ActionPerformed(evt);
            }
        });
        jPanel8.add(read3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 130, 220, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 45.png"))); // NOI18N
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 270, 150));

        jLabel5.setText("jLabel5");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/div.u-border-general--bottom.png"))); // NOI18N
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel16.setPreferredSize(new java.awt.Dimension(1319, 197));
        jLabel16.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 507, -1, -1));

        jPanel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.setDoubleBuffered(false);
        jPanel9.setEnabled(false);
        jPanel9.setFocusable(false);
        jPanel9.setOpaque(false);
        jPanel9.setRequestFocusEnabled(false);
        jPanel9.setVerifyInputWhenFocusTarget(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sampah.png"))); // NOI18N
        delete4.setBorderPainted(false);
        delete4.setContentAreaFilled(false);
        delete4.setFocusPainted(false);
        delete4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete4ActionPerformed(evt);
            }
        });
        jPanel9.add(delete4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        edit4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pencil.png"))); // NOI18N
        edit4.setBorderPainted(false);
        edit4.setContentAreaFilled(false);
        edit4.setFocusPainted(false);
        edit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit4ActionPerformed(evt);
            }
        });
        jPanel9.add(edit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, -1, -1));

        jScrollPane13.setBorder(null);
        jScrollPane13.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane13.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane13.setEnabled(false);
        jScrollPane13.setFocusable(false);
        jScrollPane13.setOpaque(false);
        jScrollPane13.setWheelScrollingEnabled(false);

        judul4.setEditable(false);
        judul4.setBackground(new java.awt.Color(255, 255, 255));
        judul4.setColumns(20);
        judul4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 23)); // NOI18N
        judul4.setRows(2);
        judul4.setText("Membangun Kesehatan Mental Bayi");
        judul4.setAutoscrolls(false);
        judul4.setBorder(null);
        judul4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        judul4.setFocusable(false);
        jScrollPane13.setViewportView(judul4);

        jPanel9.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 400, 40));

        jScrollPane14.setBorder(null);
        jScrollPane14.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane14.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane14.setFocusable(false);
        jScrollPane14.setOpaque(false);
        jScrollPane14.setWheelScrollingEnabled(false);

        desc4.setColumns(20);
        desc4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        desc4.setForeground(new java.awt.Color(111, 110, 110));
        desc4.setLineWrap(true);
        desc4.setRows(5);
        desc4.setText("Mengasuh bayi yang baru lahir adalah tugas yang berat dan orang tua akan \nmerasakan berbagai macam emosi. Bahagia bercampur dengan frustrasi, \nkeletihan, dan kecemasan. Emosi yang bercampur-aduk ini sama sekali tak \nperlu ditakuti...");
        desc4.setAutoscrolls(false);
        desc4.setBorder(null);
        desc4.setFocusable(false);
        jScrollPane14.setViewportView(desc4);

        jPanel9.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 670, 100));

        read4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        read4.setForeground(new java.awt.Color(34, 184, 185));
        read4.setText("Baca Selengkapnya..");
        read4.setActionCommand("");
        read4.setBorder(null);
        read4.setBorderPainted(false);
        read4.setContentAreaFilled(false);
        read4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        read4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read4ActionPerformed(evt);
            }
        });
        jPanel9.add(read4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 130, 220, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 45.png"))); // NOI18N
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 270, 150));

        jLabel6.setText("jLabel6");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, -1));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/div.u-border-general--bottom.png"))); // NOI18N
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel17.setPreferredSize(new java.awt.Dimension(1319, 197));
        jLabel17.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 707, -1, -1));

        semuaButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        semuaButton.setForeground(new java.awt.Color(34, 184, 185));
        semuaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 209 (1).png"))); // NOI18N
        semuaButton.setText("Semua");
        semuaButton.setBorderPainted(false);
        semuaButton.setContentAreaFilled(false);
        semuaButton.setFocusPainted(false);
        semuaButton.setFocusable(false);
        semuaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        semuaButton.setRequestFocusEnabled(false);
        semuaButton.setRolloverEnabled(false);
        semuaButton.setVerifyInputWhenFocusTarget(false);
        semuaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semuaButtonActionPerformed(evt);
            }
        });
        jPanel2.add(semuaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 180, -1));

        artikelButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        artikelButton.setForeground(new java.awt.Color(120, 120, 135));
        artikelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); // NOI18N
        artikelButton.setText("Artikel");
        artikelButton.setBorderPainted(false);
        artikelButton.setContentAreaFilled(false);
        artikelButton.setFocusPainted(false);
        artikelButton.setFocusable(false);
        artikelButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        artikelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artikelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(artikelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 40, 174, -1));

        videoButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        videoButton.setForeground(new java.awt.Color(120, 120, 135));
        videoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); // NOI18N
        videoButton.setText("Video");
        videoButton.setBorderPainted(false);
        videoButton.setContentAreaFilled(false);
        videoButton.setFocusPainted(false);
        videoButton.setFocusable(false);
        videoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        videoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoButtonActionPerformed(evt);
            }
        });
        jPanel2.add(videoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 40, 178, -1));

        unggahButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        unggahButton.setForeground(new java.awt.Color(34, 184, 185));
        unggahButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 212 (1).png"))); // NOI18N
        unggahButton.setText("    Unggah");
        unggahButton.setBorderPainted(false);
        unggahButton.setContentAreaFilled(false);
        unggahButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        unggahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unggahButtonActionPerformed(evt);
            }
        });
        jPanel2.add(unggahButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 40, 176, -1));

        prevButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn-prev.png"))); // NOI18N
        prevButton.setToolTipText("");
        prevButton.setBorder(null);
        prevButton.setBorderPainted(false);
        prevButton.setContentAreaFilled(false);
        prevButton.setFocusPainted(false);
        prevButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });
        jPanel2.add(prevButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 912, -1, -1));

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn-next.png"))); // NOI18N
        nextButton.setToolTipText("");
        nextButton.setBorder(null);
        nextButton.setBorderPainted(false);
        nextButton.setContentAreaFilled(false);
        nextButton.setFocusPainted(false);
        nextButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        jPanel2.add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(882, 912, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("1 / 5");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 920, -1, -1));

        jScrollPane2.setViewportView(jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 94));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Foto user (3).png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setPreferredSize(new java.awt.Dimension(70, 70));
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1288, 12, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Property 1=Default.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 22, -1, -1));

        berandaButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        berandaButton.setForeground(new java.awt.Color(111, 110, 110));
        berandaButton.setText("Beranda");
        berandaButton.setBorderPainted(false);
        berandaButton.setContentAreaFilled(false);
        berandaButton.setPreferredSize(new java.awt.Dimension(78, 15));
        berandaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berandaButtonActionPerformed(evt);
            }
        });
        jPanel1.add(berandaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 40, 100, -1));

        navBarTwo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        navBarTwo.setForeground(new java.awt.Color(111, 110, 110));
        navBarTwo.setText("Manajemen Jadwal");
        navBarTwo.setBorderPainted(false);
        navBarTwo.setContentAreaFilled(false);
        navBarTwo.setPreferredSize(new java.awt.Dimension(180, 15));
        navBarTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navBarTwoActionPerformed(evt);
            }
        });
        jPanel1.add(navBarTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        navBarThree.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        navBarThree.setForeground(new java.awt.Color(111, 110, 110));
        navBarThree.setText("Sesi Konsultasi");
        navBarThree.setBorderPainted(false);
        navBarThree.setContentAreaFilled(false);
        navBarThree.setPreferredSize(new java.awt.Dimension(143, 15));
        navBarThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navBarThreeActionPerformed(evt);
            }
        });
        jPanel1.add(navBarThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        navBarFour.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        navBarFour.setForeground(new java.awt.Color(111, 110, 110));
        navBarFour.setText("Obrolan");
        navBarFour.setBorderPainted(false);
        navBarFour.setContentAreaFilled(false);
        navBarFour.setPreferredSize(new java.awt.Dimension(76, 15));
        navBarFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navBarFourActionPerformed(evt);
            }
        });
        jPanel1.add(navBarFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 40, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        // TODO add your handling code here:
        ImageIcon iconButton8 = (ImageIcon) artikelButton.getIcon();
        ImageIcon iconReference = new ImageIcon(getClass().getResource("/images/Frame 209 (1).png"));
        ImageIcon iconButton9 = (ImageIcon) videoButton.getIcon();

        if (iconButton8 != null && iconButton8.getDescription().equals(iconReference.getDescription())) {
             Aplikasi.delArtikel.hapusArtikelDariDB(judul1.getText());
             List<Artikel> artikels = Aplikasi.controllerManajemen.loadArticle(pageArtikel);
            Aplikasi.controllerManajemen.showArticle(artikels);             
        } else if (iconButton9 != null && iconButton9.getDescription().equals(iconReference.getDescription())){
            Aplikasi.delVidio.hapusVideoDariDB(judul1.getText());
            List<Video> videos = Aplikasi.controllerManajemen.loadVideo(pageVideo);
            Aplikasi.controllerManajemen.showVideo(videos);            
        } else {
           Aplikasi.dialogUI.showMessage("");
        }
       
        
    }//GEN-LAST:event_delete1ActionPerformed

    private void Edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit1ActionPerformed
        // TODO add your handling code here:
        //ini harusnya cek kondisi dulu jenis kontennya artikel atau video?
        // klu artikel manggil editArtikel, klu video manggil edit video
        //logicnya mungkin mirip sm tombol unggah
        //ini blum ada kelas editVideonya sm editVideoController aja
        if(Aplikasi.controllerManajemen.getType(jLabel3.getText(), judul1.getText()).equals("artikel")){
            Aplikasi.updateArtikel.showArticleEdit(judul1.getText(), jLabel3.getText());
            this.dispose();
        }else if(Aplikasi.controllerManajemen.getType(jLabel3.getText(), judul1.getText()).equals("video")){
            Aplikasi.updateVideo.showVideoEdit(judul1.getText(), jLabel3.getText());
            this.dispose();
        }
    }//GEN-LAST:event_Edit1ActionPerformed

    private void read1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read1ActionPerformed
        // TODO add your handling code here:
        if(Aplikasi.controllerManajemen.getType(jLabel3.getText(), judul1.getText()).equals("artikel")){
           Aplikasi.lihatKonten.showArticle(judul1.getText());        
           this.dispose();
        }else if(Aplikasi.controllerManajemen.getType(jLabel3.getText(), judul1.getText()).equals("video")){
            Aplikasi.dialogUI.showMessage("Fitur ini tidak diimplementasikan");
        }
    }//GEN-LAST:event_read1ActionPerformed

    private void delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete2ActionPerformed
        // TODO add your handling code here:
        ImageIcon iconButton8 = (ImageIcon) artikelButton.getIcon();
        ImageIcon iconReference = new ImageIcon(getClass().getResource("/images/Frame 209 (1).png"));
        ImageIcon iconButton9 = (ImageIcon) videoButton.getIcon();

        if (iconButton8 != null && iconButton8.getDescription().equals(iconReference.getDescription())) {
             Aplikasi.delArtikel.hapusArtikelDariDB(judul2.getText());
             List<Artikel> artikels = Aplikasi.controllerManajemen.loadArticle(pageArtikel);
            Aplikasi.controllerManajemen.showArticle(artikels);             
        } else if (iconButton9 != null && iconButton9.getDescription().equals(iconReference.getDescription())){
            Aplikasi.delVidio.hapusVideoDariDB(judul2.getText());
            List<Video> videos = Aplikasi.controllerManajemen.loadVideo(pageVideo);
            Aplikasi.controllerManajemen.showVideo(videos);            
        } else {
           Aplikasi.dialogUI.showMessage("");
        }
    }//GEN-LAST:event_delete2ActionPerformed

    private void edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit2ActionPerformed
       //ini harusnya cek kondisi dulu jenis kontennya artikel atau video?
        // klu artikel manggil editArtikel, klu video manggil edit video
        //logicnya mungkin mirip sm tombol unggah
        //ini blum ada kelas editVideonya sm editVideoController aja
        if(Aplikasi.controllerManajemen.getType(jLabel4.getText(), judul2.getText()).equals("artikel")){
            Aplikasi.updateArtikel.showArticleEdit(judul2.getText(), jLabel4.getText());
            this.dispose();
        }else if(Aplikasi.controllerManajemen.getType(jLabel4.getText(), judul2.getText()).equals("video")){
            Aplikasi.updateVideo.showVideoEdit(judul2.getText(), jLabel4.getText());
            this.dispose();
        }        
    }//GEN-LAST:event_edit2ActionPerformed

    private void read2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read2ActionPerformed
        // TODO add your handling code here:
        if(Aplikasi.controllerManajemen.getType(jLabel4.getText(), judul2.getText()).equals("artikel")){
           Aplikasi.lihatKonten.showArticle(judul2.getText());        
            this.dispose();
        }else if(Aplikasi.controllerManajemen.getType(jLabel4.getText(), judul2.getText()).equals("video")){
            Aplikasi.dialogUI.showMessage("Fitur ini tidak diimplementasikan");
        }        
    }//GEN-LAST:event_read2ActionPerformed

    private void delete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete3ActionPerformed
        // TODO add your handling code here:
        ImageIcon iconButton8 = (ImageIcon) artikelButton.getIcon();
        ImageIcon iconReference = new ImageIcon(getClass().getResource("/images/Frame 209 (1).png"));
        ImageIcon iconButton9 = (ImageIcon) videoButton.getIcon();

        if (iconButton8 != null && iconButton8.getDescription().equals(iconReference.getDescription())) {
             Aplikasi.delArtikel.hapusArtikelDariDB(judul3.getText());
             List<Artikel> artikels = Aplikasi.controllerManajemen.loadArticle(pageArtikel);
            Aplikasi.controllerManajemen.showArticle(artikels);             
        } else if (iconButton9 != null && iconButton9.getDescription().equals(iconReference.getDescription())){
            Aplikasi.delVidio.hapusVideoDariDB(judul3.getText());
            List<Video> videos = Aplikasi.controllerManajemen.loadVideo(pageVideo);
            Aplikasi.controllerManajemen.showVideo(videos);            
        } else {
           Aplikasi.dialogUI.showMessage("");
        }
    }//GEN-LAST:event_delete3ActionPerformed

    private void edit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit3ActionPerformed
        //ini harusnya cek kondisi dulu jenis kontennya artikel atau video?
        // klu artikel manggil editArtikel, klu video manggil edit video
        //logicnya mungkin mirip sm tombol unggah
        //ini blum ada kelas editVideonya sm editVideoController aja
        if(Aplikasi.controllerManajemen.getType(jLabel5.getText(), judul3.getText()).equals("artikel")){
            Aplikasi.updateArtikel.showArticleEdit(judul3.getText(), jLabel5.getText());
            this.dispose();
        }else if(Aplikasi.controllerManajemen.getType(jLabel5.getText(), judul3.getText()).equals("video")){
            Aplikasi.updateVideo.showVideoEdit(judul3.getText(), jLabel5.getText());
            this.dispose();
        }
    }//GEN-LAST:event_edit3ActionPerformed

    private void read3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read3ActionPerformed
        // TODO add your handling code here:
        if(Aplikasi.controllerManajemen.getType(jLabel5.getText(), judul3.getText()).equals("artikel")){
           Aplikasi.lihatKonten.showArticle(judul3.getText());        
           this.dispose();
        }else if(Aplikasi.controllerManajemen.getType(jLabel5.getText(), judul3.getText()).equals("video")){
            Aplikasi.dialogUI.showMessage("Fitur ini tidak diimplementasikan");
        }       
        
    }//GEN-LAST:event_read3ActionPerformed

    private void delete4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete4ActionPerformed
        // TODO add your handling code here:
        ImageIcon iconButton8 = (ImageIcon) artikelButton.getIcon();
        ImageIcon iconReference = new ImageIcon(getClass().getResource("/images/Frame 209 (1).png"));
        ImageIcon iconButton9 = (ImageIcon) videoButton.getIcon();

        if (iconButton8 != null && iconButton8.getDescription().equals(iconReference.getDescription())) {
             Aplikasi.delArtikel.hapusArtikelDariDB(judul4.getText());
             List<Artikel> artikels = Aplikasi.controllerManajemen.loadArticle(pageArtikel);
            Aplikasi.controllerManajemen.showArticle(artikels);             
        } else if (iconButton9 != null && iconButton9.getDescription().equals(iconReference.getDescription())){
            Aplikasi.delVidio.hapusVideoDariDB(judul4.getText());
            List<Video> videos = Aplikasi.controllerManajemen.loadVideo(pageVideo);
            Aplikasi.controllerManajemen.showVideo(videos);            
        } else {
           Aplikasi.dialogUI.showMessage("");
        }
    }//GEN-LAST:event_delete4ActionPerformed

    private void edit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit4ActionPerformed
        //ini harusnya cek kondisi dulu jenis kontennya artikel atau video?
        // klu artikel manggil editArtikel, klu video manggil edit video
        //logicnya mungkin mirip sm tombol unggah
        //ini blum ada kelas editVideonya sm editVideoController aja
        if(Aplikasi.controllerManajemen.getType(jLabel6.getText(), judul4.getText()).equals("artikel")){
            Aplikasi.updateArtikel.showArticleEdit(judul4.getText(), jLabel6.getText());
            this.dispose();
        }else if(Aplikasi.controllerManajemen.getType(jLabel6.getText(), judul4.getText()).equals("video")){
            Aplikasi.updateVideo.showVideoEdit(judul4.getText(), jLabel6.getText());
            this.dispose();
        }
    }//GEN-LAST:event_edit4ActionPerformed

    private void read4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read4ActionPerformed
        // TODO add your handling code here:
        if(Aplikasi.controllerManajemen.getType(jLabel6.getText(), judul4.getText()).equals("artikel")){
           Aplikasi.lihatKonten.showArticle(judul4.getText());        
           this.dispose();
        }else if(Aplikasi.controllerManajemen.getType(jLabel6.getText(), judul4.getText()).equals("video")){
            Aplikasi.dialogUI.showMessage("Fitur ini tidak diimplementasikan");
        }     
        
    }//GEN-LAST:event_read4ActionPerformed

    private void semuaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semuaButtonActionPerformed
        currentShowing = "all";        
        int totalPagesAll = (int) Math.ceil((Aplikasi.article.totalArticle() + Aplikasi.video.totalVideos()) / 4.0);
        if(totalPagesAll==0){
            jLabel1.setText("1/1");
        }else{
            jLabel1.setText("1/"+totalPagesAll);
        }
        semuaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 209 (1).png")));
        artikelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        artikelButton.setForeground(new java.awt.Color(120, 120, 135));
        videoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        videoButton.setForeground(new java.awt.Color(120, 120, 135));
        semuaButton.setForeground(new java.awt.Color(34, 184, 185));
               
        //menampilkan semua
        unggahButton.setVisible(false);
        Edit1.setVisible(false);
        edit2.setVisible(false);
        edit3.setVisible(false);
        edit4.setVisible(false);
        Aplikasi.controllerManajemen.showAll(1);        
        
    }//GEN-LAST:event_semuaButtonActionPerformed

    private void artikelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artikelButtonActionPerformed
        currentShowing = "artikel";
        if(Aplikasi.article.getTotalPages()==0){
            jLabel1.setText("1/1");
        }else{
            jLabel1.setText("1/"+Aplikasi.article.getTotalPages());
        }
        artikelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 209 (1).png"))); 
        artikelButton.setForeground(new java.awt.Color(34, 184, 185));
        semuaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        semuaButton.setForeground(new java.awt.Color(120, 120, 135));
        videoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        videoButton.setForeground(new java.awt.Color(120, 120, 135));
      
        //memanggil tampilkanHanya artikel
        if(Aplikasi.akun.getPerson().equals("administrator")){
            unggahButton.setVisible(true);
            Edit1.setVisible(true);
            edit2.setVisible(true);
            edit3.setVisible(true);
            edit4.setVisible(true);
            delete1.setVisible(true);
            delete2.setVisible(true);
            delete3.setVisible(true);
            delete4.setVisible(true);
        }else{
            unggahButton.setVisible(false);
        }
        List<Artikel> artikels = Aplikasi.controllerManajemen.loadArticle(1);
        Aplikasi.controllerManajemen.showArticle(artikels);
        //this.dispose();
        
    }//GEN-LAST:event_artikelButtonActionPerformed

    private void videoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoButtonActionPerformed
        currentShowing ="video";
        if(Aplikasi.video.getTotalPages()==0){
            jLabel1.setText("1/1");
        }else{
            jLabel1.setText("1/"+Aplikasi.video.getTotalPages());
        }
        videoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 209 (1).png"))); 
        videoButton.setForeground(new java.awt.Color(34, 184, 185));
        artikelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        artikelButton.setForeground(new java.awt.Color(120, 120, 135));
        semuaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        semuaButton.setForeground(new java.awt.Color(120, 120, 135));
        
        //memanggil tampilkan hanyaa video
        if(Aplikasi.akun.getPerson().equals("administrator")){
            unggahButton.setVisible(true);
            Edit1.setVisible(true);
            edit2.setVisible(true);
            edit3.setVisible(true);
            edit4.setVisible(true);
            delete1.setVisible(true);
            delete2.setVisible(true);
            delete3.setVisible(true);
            delete4.setVisible(true);
        }else{
            unggahButton.setVisible(false);
        }
        List<Video> videos = Aplikasi.controllerManajemen.loadVideo(1);
        Aplikasi.controllerManajemen.showVideo(videos);
        //this.dispose();
    }//GEN-LAST:event_videoButtonActionPerformed

    private void unggahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unggahButtonActionPerformed
        
        JButton temp = new javax.swing.JButton();
        temp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 209 (1).png"))); // NOI18N
        ImageIcon iconButton8 = (ImageIcon) artikelButton.getIcon();
        ImageIcon iconReference = new ImageIcon(getClass().getResource("/images/Frame 209 (1).png"));
        ImageIcon iconButton9 = (ImageIcon) videoButton.getIcon();

        if (iconButton8 != null && iconButton8.getDescription().equals(iconReference.getDescription())) {
            Aplikasi.addArticle.showUpArticle();
        } else if (iconButton9 != null && iconButton9.getDescription().equals(iconReference.getDescription())){
            Aplikasi.addVideo.showUpVideo();
        } else {
           Aplikasi.dialogUI.showMessage("");
        }
    }//GEN-LAST:event_unggahButtonActionPerformed

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        if(currentShowing.equals("all")){
            if(pageAll > 1) {  
                pageAll--;
                int totalPagesAll = (int) Math.ceil((Aplikasi.article.totalArticle() + Aplikasi.video.totalVideos()) / 4.0);
                jLabel1.setText(pageAll + "/" + totalPagesAll );
                Aplikasi.controllerManajemen.showAll(pageAll);
                
            }
        } else if(currentShowing.equals("video")){
            if(pageVideo > 1) {  
                pageVideo--; 
                jLabel1.setText(pageVideo+"/"+Aplikasi.video.getTotalPages());
                List<Video> videos = Aplikasi.controllerManajemen.loadVideo(pageVideo); // Beri parameter pageVideo
                Aplikasi.controllerManajemen.showVideo(videos);
            }
        } else if(currentShowing.equals("artikel")){
            if(pageArtikel > 1) {  
                pageArtikel--;  
                jLabel1.setText(pageArtikel +"/"+Aplikasi.article.getTotalPages());
                List<Artikel> articles = Aplikasi.controllerManajemen.loadArticle(pageArtikel); 
                Aplikasi.controllerManajemen.showArticle(articles);
            }
        }
                
    }//GEN-LAST:event_prevButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        if(currentShowing.equals("all")){           
            int totalPagesAll = (int) Math.ceil((Aplikasi.article.totalArticle() + Aplikasi.video.totalVideos()) / 4.0);
            if (pageAll < totalPagesAll) { 
                pageAll++;
                jLabel1.setText(pageAll + "/" + totalPagesAll );
                Aplikasi.controllerManajemen.showAll(pageAll);
            }
        } else if(currentShowing.equals("video")){
            if(pageVideo+1 <= Aplikasi.video.getTotalPages()){
                pageVideo++;
                jLabel1.setText(pageVideo+"/"+Aplikasi.video.getTotalPages());
                List<Video> videos = Aplikasi.controllerManajemen.loadVideo(pageVideo);
                Aplikasi.controllerManajemen.showVideo(videos);
            }
        }else {
            if(pageArtikel+1 <= Aplikasi.article.getTotalPages()){
                pageArtikel++;
                jLabel1.setText(pageArtikel +"/"+Aplikasi.article.getTotalPages());
                List<Artikel> articles = Aplikasi.controllerManajemen.loadArticle(pageArtikel); 
                Aplikasi.controllerManajemen.showArticle(articles);
            }
        }        
    }//GEN-LAST:event_nextButtonActionPerformed

    private void berandaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berandaButtonActionPerformed
        // TODO add your handling code here:
        Aplikasi.beranda.tampilkan();
        this.dispose();
    }//GEN-LAST:event_berandaButtonActionPerformed

    private void navBarTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navBarTwoActionPerformed
        // TODO add your handling code here:
        if(Aplikasi.akun.getPerson().contains("k")){
            Aplikasi.dialogUI.showMessage("FITUR INI TIDAK KAMI PROSES");
        }else{
            //manajemen konten
            Aplikasi.controllerManajemen.showAll(pageAll);            
        }
    }//GEN-LAST:event_navBarTwoActionPerformed

    private void navBarThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navBarThreeActionPerformed
        // TODO add your handling code here:
        if(Aplikasi.akun.getPerson().contains("k")){
            this.dispose();
            Aplikasi.controllerDaftarSesi.load();
        }else if(Aplikasi.akun.getPerson().contains("admin")){
            Aplikasi.dialogUI.showMessage("FITUR INI TIDAK KAMI PROSES");
        }
    }//GEN-LAST:event_navBarThreeActionPerformed

    private void navBarFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navBarFourActionPerformed
        // TODO add your handling code here:-
        Aplikasi.dialogUI.showMessage("FITUR INI TIDAK KAMI PROSES");
    }//GEN-LAST:event_navBarFourActionPerformed

   
    public void tampilkanArticle(List<Artikel> Articles){        
        int totalPages = Aplikasi.article.getTotalPages();
        List <Artikel> articles = Articles;
                
        
        if(Aplikasi.akun.getPerson().equals("administrator")){
            unggahButton.setVisible(true);
        }else{
            unggahButton.setVisible(false);
            delete1.setVisible(false);
            Edit1.setVisible(false);
            delete2.setVisible(false);
            edit2.setVisible(false);
            delete3.setVisible(false);
            edit3.setVisible(false);
            delete4.setVisible(false);
            edit4.setVisible(false);
        }
        tampilkan();  
        
        artikelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 209 (1).png"))); 
        artikelButton.setForeground(new java.awt.Color(34, 184, 185));
        semuaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        semuaButton.setForeground(new java.awt.Color(120, 120, 135));
        videoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        videoButton.setForeground(new java.awt.Color(120, 120, 135));
        
        if(articles.size() >=1){
            Artikel artikel = articles.get(0);
            String path = "src/main/resources/images/Thumbnail_db_" + artikel.judul + ".png";
            jLabel28.setIcon(new javax.swing.ImageIcon(path));                     
            judul1.setText(artikel.getJudul());
            if(artikel.getIsiArtikel().length()>100){
                desc1.setText(artikel.getIsiArtikel().substring(0,100)+"...");
            }else{
                desc1.setText(artikel.getIsiArtikel() + "...");
            }
            jPanel6.setVisible(true);
            jLabel3.setText(artikel.getIdArtikel());
            jLabel3.setVisible(false);
        }
        if(articles.size() >=2){
            Artikel artikel = articles.get(1);
            String path = "src/main/resources/images/Thumbnail_db_" + artikel.judul + ".png";
            jLabel29.setIcon(new javax.swing.ImageIcon(path));         
            judul2.setText(artikel.getJudul());
            if(artikel.getIsiArtikel().length()>100){
                desc2.setText(artikel.getIsiArtikel().substring(0,100)+"...");
            }else{
                desc2.setText(artikel.getIsiArtikel()+"...");
            }
            jPanel7.setVisible(true);
            jLabel4.setText(artikel.getIdArtikel());
            jLabel4.setVisible(false);
        }
        if(articles.size() >=3){
            Artikel artikel = articles.get(2); 
            String path = "src/main/resources/images/Thumbnail_db_" + artikel.judul + ".png";
            jLabel30.setIcon(new javax.swing.ImageIcon(path));        
            judul3.setText(artikel.getJudul());
            if(artikel.getIsiArtikel().length()>100){
                desc3.setText(artikel.getIsiArtikel().substring(0,100)+"...");
            }else{
                desc3.setText(artikel.getIsiArtikel()+"...");
            }
            jPanel8.setVisible(true);
            jLabel5.setText(artikel.getIdArtikel());
            jLabel5.setVisible(false);
        }
        if(articles.size() >=4){
            Artikel artikel = articles.get(3);            
            String path = "src/main/resources/images/Thumbnail_db_" + artikel.judul + ".png";
            jLabel31.setIcon(new javax.swing.ImageIcon(path));            
            judul4.setText(artikel.getJudul());
            if(artikel.getIsiArtikel().length()>100){
                desc4.setText(artikel.getIsiArtikel().substring(0,100)+"...");
            }else{
                desc4.setText(artikel.getIsiArtikel()+"...");
            }
            jPanel9.setVisible(true);
            jLabel6.setText(artikel.getIdArtikel());
            jLabel6.setVisible(false);
        }
        
        this.setVisible(true);
    }
           
    
    public void tampilkanVideo(List<Video> Videos){        
        if(Aplikasi.akun.getPerson().equals("administrator")){
            unggahButton.setVisible(true);
        }else{
            unggahButton.setVisible(false);
            delete1.setVisible(false);
            Edit1.setVisible(false);
            delete2.setVisible(false);
            edit2.setVisible(false);
            delete3.setVisible(false);
            edit3.setVisible(false);
            delete4.setVisible(false);
            edit4.setVisible(false);
        }
        
        tampilkan(); 
        videoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 209 (1).png"))); 
        videoButton.setForeground(new java.awt.Color(34, 184, 185));
        artikelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        artikelButton.setForeground(new java.awt.Color(120, 120, 135));
        semuaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        semuaButton.setForeground(new java.awt.Color(120, 120, 135));
        
        if(Videos.size()>=1){
            Video video = Videos.get(0);
            String path = "src/main/resources/images/Thumbnail_db_" + video.judul + ".png";
            jLabel28.setIcon(new javax.swing.ImageIcon(path));       
            judul1.setText(video.getJudul());
            String deskripsi = video.getDeskripsi().substring(0, Math.min(100, video.getDeskripsi().length()));
            desc1.setText(deskripsi);         
            
            jLabel3.setText(video.getIdVideo());
            jPanel6.setVisible(true);
        }
        if(Videos.size()>=2){
            Video video = Videos.get(1);
            String path = "src/main/resources/images/Thumbnail_db_" + video.judul + ".png";
            jLabel29.setIcon(new javax.swing.ImageIcon(path));     
            judul2.setText(video.getJudul());
            String deskripsi = video.getDeskripsi().substring(0, Math.min(100, video.getDeskripsi().length()));
            desc2.setText(deskripsi);  
            
            jLabel4.setText(video.getIdVideo());
            jPanel7.setVisible(true);
        }
        if(Videos.size()>=3){
            Video video = Videos.get(2);            
            String path = "src/main/resources/images/Thumbnail_db_" + video.judul + ".png";
            jLabel30.setIcon(new javax.swing.ImageIcon(path));     
            judul3.setText(video.getJudul());
            String deskripsi = video.getDeskripsi().substring(0, Math.min(100, video.getDeskripsi().length()));
            desc3.setText(deskripsi); 
            
            jLabel5.setText(video.getIdVideo());
            jPanel8.setVisible(true);
        }
        if(Videos.size()>=4){
            Video video = Videos.get(3);            
            String path = "src/main/resources/images/Thumbnail_db_" + video.judul + ".png";
            jLabel31.setIcon(new javax.swing.ImageIcon(path));     
            judul4.setText(video.getJudul());
            String deskripsi = video.getDeskripsi().substring(0, Math.min(100, video.getDeskripsi().length()));
            desc4.setText(deskripsi);       
            
            jLabel6.setText(video.getIdVideo());
            jPanel9.setVisible(true);
        }
        
        
        
        this.setVisible(true);
    }
    
    public void tampilkanSemua(List<Content> all){       
        tampilkan();
        int totalPagesAll = (int) Math.ceil((Aplikasi.article.totalArticle() + Aplikasi.video.totalVideos()) / 4.0);
        if(totalPagesAll==0){
            jLabel1.setText("1/1");
        }else{
            jLabel1.setText("1/"+totalPagesAll);
        }
        semuaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 209 (1).png"))); 
        semuaButton.setForeground(new java.awt.Color(34, 184, 185));
        artikelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        artikelButton.setForeground(new java.awt.Color(120, 120, 135));
        videoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 210.png"))); 
        videoButton.setForeground(new java.awt.Color(120, 120, 135));
        
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        unggahButton.setVisible(false);
        delete1.setVisible(false);
        Edit1.setVisible(false);
        delete2.setVisible(false);
        edit2.setVisible(false);
        delete3.setVisible(false);
        edit3.setVisible(false);
        delete4.setVisible(false);
        edit4.setVisible(false);
        for (int i = 0; i < Math.min(4, all.size()); i++) {
        Content content = all.get(i);
        String imagePath;
        String description;
        String id;

        // Tentukan ikon dan teks berdasarkan tipe konten
        if (content instanceof Video video) {
            imagePath = "src/main/resources/images/Thumbnail_db_" + video.getJudul() + ".png";
            description = video.getDeskripsi();            
            id = video.getIdVideo();
        } else if (content instanceof Artikel artikel) {
            imagePath = "src/main/resources/images/Thumbnail_db_" + artikel.getJudul() + ".png";
            description = artikel.getIsiArtikel().substring(0, Math.min(100, artikel.getIsiArtikel().length())) + "...";
            id = artikel.getIdArtikel();
        } else {
            continue; // Jika tipe tidak dikenali, lewati
        }

        // Atur konten ke panel yang sesuai
        switch (i) {
            case 0 -> {
                jLabel28.setIcon(new javax.swing.ImageIcon(imagePath));
                judul1.setText(content.getJudul());
                desc1.setText(description);
                jLabel3.setText(id);
                jPanel6.setVisible(true);
            }
            case 1 -> {
                jLabel29.setIcon(new javax.swing.ImageIcon(imagePath));
                judul2.setText(content.getJudul());
                desc2.setText(description);
                jLabel4.setText(id);
                jPanel7.setVisible(true);
            }
            case 2 -> {
                jLabel30.setIcon(new javax.swing.ImageIcon(imagePath));
                judul3.setText(content.getJudul());
                desc3.setText(description);
                jLabel5.setText(id);
                jPanel8.setVisible(true);
            }
            case 3 -> {
                jLabel31.setIcon(new javax.swing.ImageIcon(imagePath));
                judul4.setText(content.getJudul());
                desc4.setText(description);
                jLabel6.setText(id);
                jPanel9.setVisible(true);
            }
        }
    }     
           
        this.setVisible(true);
    }
    
    public void tampilkan(){        
        if(Aplikasi.akun.getPerson().equals("klien")){
            navBarTwo.setText("Reservasi");            
        }else if(Aplikasi.akun.getPerson().equals("administrator")){
            navBarThree.setText("Notifikasi");
            navBarFour.setVisible(false);
            navBarTwo.setText("Manajemen Konten");      
          
        }
        
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        
    }
    
   
    
    
    
    /**
     * @param args the command line arguments
     */

    public JButton getjButton13() {
        return delete1;
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit1;
    private javax.swing.JButton artikelButton;
    private javax.swing.JButton berandaButton;
    private javax.swing.JButton delete1;
    private javax.swing.JButton delete2;
    private javax.swing.JButton delete3;
    private javax.swing.JButton delete4;
    private javax.swing.JTextArea desc1;
    private javax.swing.JTextArea desc2;
    private javax.swing.JTextArea desc3;
    private javax.swing.JTextArea desc4;
    private javax.swing.JButton edit2;
    private javax.swing.JButton edit3;
    private javax.swing.JButton edit4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea judul1;
    private javax.swing.JTextArea judul2;
    private javax.swing.JTextArea judul3;
    private javax.swing.JTextArea judul4;
    private javax.swing.JButton navBarFour;
    private javax.swing.JButton navBarThree;
    private javax.swing.JButton navBarTwo;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton prevButton;
    private javax.swing.JButton read1;
    private javax.swing.JButton read2;
    private javax.swing.JButton read3;
    private javax.swing.JButton read4;
    private javax.swing.JButton semuaButton;
    private javax.swing.JButton unggahButton;
    private javax.swing.JButton videoButton;
    // End of variables declaration//GEN-END:variables
}
